catcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [ 
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cat_index, name='cat-index'),
    path('cats/<int:cat_id>/', views.cat_detail, name = "cat-detail"),
    path('cats/create/', views.CatCreate.as_view(), name="cat-create"),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cat-update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cat-delete'),
    path(
        'cats/<int:cat_id>/add-feeding/', 
        views.add_feeding, 
        name='add-feeding'
    ),
]  

main_app/models.py
from django.db import models
from django.urls import reverse


MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)





class Cat (models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()



def __str__(self):
      return self.name 
    
def get_absolute_url(self):
        return reverse("cat-detail", kwargs={"cat_id": self.id})
    
    
class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

  

    # Create a cat_id column for each feeding in the database
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date'] 

main_app/forms.py
from django import forms
from .models import Feeding

class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
from django.http import HttpResponse 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Cat
from .forms import FeedingForm
from django.shortcuts import render, redirect


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cat_index(request):
    cats = Cat.objects.all()
    return render(request, 'cats/index.html', {'cats': cats})

def cat_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    # instantiate FeedingForm to be rendered in the template
    feeding_form = FeedingForm()
    return render(request, 'cats/detail.html', {
        # include the cat and feeding_form in the context
        'cat': cat, 'feeding_form': feeding_form
    })

def add_feeding(request, cat_id):
    # create a ModelForm instance using the data in request.POST
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the cat_id assigned
        new_feeding = form.save(commit=False)
        new_feeding.cat_id = cat_id
        new_feeding.save()
    return redirect('cat-detail', cat_id=cat_id) 



class CatUpdate(UpdateView):
    model = Cat
    # Let's disallow the renaming of a cat by excluding the name field!
    fields = ['breed', 'description', 'age']
    success_url = "/cats/"

class CatDelete(DeleteView):
    model = Cat
    success_url = '/cats/'

class CatCreate(CreateView):
    model = Cat
    fields = '__all__'
    success_url = "/cats/"

main_app/templates/about.html
{% extends 'base.html' %}


{% block content %}

    <h1>About the Cat Collector 🐈</h1> 

    <hr />

    <p class="page-content">
        This is some stuff about the cat Collector.
    </p>

{% endblock %}    

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/splash.svg' %}">
  <title>Cat Collector</title>
  {% block head %}
  {% endblock %}
</head>
<body>
  <header>
    <div class="header-logo-container">
      <a href="/">
        <img src="{% static 'images/header-logo.svg' %}" alt="Cat Collector Logo">
      </a>
    </div>
    <nav>
      <ul>
        <li><a href="{% url 'cat-index' %}">All Cats</a></li>
        <li><a href="{% url 'cat-create' %}">Add a Cat</a></li>
        <li><a href="{% url 'about' %}">About</a></li>
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}

<link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
{% endblock %} 

{% block content %}

<section class="cat-container">

  <div class="cat-img">
    <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
  </div>
  <div class="cat-details">
    <h1>{{ cat.name }}</h1>
    {% if cat.age > 0 %}
      <h2>A {{ cat.age }} year old {{ cat.breed }}</h2>
    {% else %}
      <h2>A {{ cat.breed }} kitten.</h2>
    {% endif %}
    <p>{{ cat.description }}</p>
  </div>

   <div class="cat-actions">
    <a href="{% url 'cat-update' cat.id %}" class="btn warn">Edit</a>
    <a href="{% url 'cat-delete' cat.id %}" class="btn danger">Delete</a>
  </div>

</section>

<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Feedings</h2>
      <img
        src="{% static 'images/cat-cone.svg' %}"
        alt="An ice cream cone cat"
      />
      <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
      <img
        src="{% static 'images/kitty-kabob.svg' %}"
        alt="A kabob of kittens"
      />
    </div>

<h3>Add a Feeding</h3>
<form
  action="{% url 'add-feeding' cat.id %}"
  method="post"
  class="subsection-content"
  autocomplete="off"
>
  {% csrf_token %} 
  {{ feeding_form.as_p }}
  <button type="submit" class="btn submit">Add Feeding</button>
</form>

    <h3>Past Feedings</h3>
{% if cat.feeding_set.all.count %}
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Meal</th>
      </tr>
    </thead>
    <tbody>
      {% for feeding in cat.feeding_set.all %}
      <tr>
        <td>{{feeding.date}}</td>
        <td>{{feeding.get_meal_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <div class="subsection-content">
    <p>⚠️ {{cat.name}} has not been fed!</p>
  </div>
{% endif %}
{% endblock %}

main_app/templates/cats/index.html
{% extends "base.html" %}
{% load static %} 


 {% block head %}
          <link rel="stylesheet" href="{% static 'css/cats/cat-index.css' %}">
  {% endblock %}


{% block content %}

     <section class="page-header">
            <h1>Cat List</h1>
            <img
    src="{% static 'images/cool-cat.svg' %}"
    alt="A cool cat"
  />
  <img
    src="{% static 'images/happy-cat.svg' %}"
    alt="A happy cat"
  />
  <img
    src="{% static 'images/teacup-cat.svg' %}"
    alt="A cat in a teacup"
  />
  <img
    src="{% static 'images/cat-in-box.svg' %}"
    alt="A cat in a box"
  />
     </section>

      <section class="card-container">
           {% for cat in cats %}

            <a href="{% url  'cat-detail' cat.id %}">

  <div class="card">
    <div class="card-content">
      
      <div class="card-img-container">
        <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="">
      </div>
      
      <h2 class="card-title">{{ cat.name }}</h2>
      {% if cat.age > 0 %}
      <p>A {{cat.age}} year old {{ cat.breed }}.</p>
      {% else %}
      <p>A {{ cat.breed }} kitten.</p>
      {% endif %}
      
      <p><small>{{ cat.description }}</small></p>
      
      </div>
    </div>
    </a> 
  {% endfor %}

      </section>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/home.css' %}"
/>
{% endblock %} {% block content %}

<section class="logo-container">
  <div class="cat-container">
    <img
      src="{% static 'images/splash.svg' %}"
      alt="The Cat Collector Cat"
    />
  </div>
  <img
    src="{% static 'images/logotype.svg' %}"
    alt="Text reads: Cat Collector"
  />
</section>

{% endblock %} 

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Cat?</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>

<h2>Are you sure you want to delete {{ cat.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'cat-detail' cat.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %} 

main_app/templates/main_app/cat_form.html
{% extends "base.html" %} 

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 

{% block content %}
<div class="page-header">
  {% if object %}
    <h1>Edit {{ object.name }}</h1>
  {% else %}
    <h1>Add a Cat</h1>
  {% endif %}
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer">
</div>
<form method="post" class="form-container">
  {% csrf_token %}
    <table>
      {{form.as_table}}
    </table>
    <button type="submit" class="btn">Submit</button>
</form>
{% endblock %} 